name: Integration Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore Dependencies
      working-directory: ./BookApp
      run: dotnet restore

    - name: Build Solution
      working-directory: ./BookApp
      run: dotnet build --configuration Release

    - name: Run Integration Tests
      env:
        JwtKey: ${{ secrets.JwtKey }}
      working-directory: ./BookApp
      run: dotnet test --filter Category=Integration
